name: Build static application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: NPM install
        run: npm install

      - name: NPM run build
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vue-app
          path: |
            dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download built vue-app
        uses: actions/download-artifact@v2
        with:
          name: vue-app
          path: dist
