name: Build and deploy application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: NPM install
        run: npm install

      - name: NPM run build
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vue-app
          path: |
            dist

  container:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download built vue-app
        uses: actions/download-artifact@v2
        with:
          name: vue-app
          path: dist
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u doerfli --password-stdin
      - uses: rlespinasse/github-slug-action@v2.x
      - run: docker build -t ghcr.io/doerfli/covid-numbers:${{ env.GITHUB_REF_SLUG }} .
      - run: docker push ghcr.io/doerfli/covid-numbers:${{ env.GITHUB_REF_SLUG }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Download built vue-app
        uses: actions/download-artifact@v2
        with:
          name: vue-app
          path: dist
      - name: Heroku deploy to covid19-data-prod
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "covid19-data-prod"
          heroku_email: "linux@doerf.li"
          usedocker: true
