name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Yarn install
        run: yarn install
      - name: Yarn run build
        run: yarn run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vue-app
          path: |
            dist
