name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built vue-app
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Deploy to Github pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
