name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Yarn install
        run: yarn install
      - name: Yarn run build
        run: yarn run build
      - name: Deploy to Github pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
