name: Deploy to Heroku Staging

on: workflow_dispatch


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Heroku deploy to covid19-data-staging
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "covid19-data-staging"
          heroku_email: "linux@doerf.li"
          usedocker: true
